"""Init2

Revision ID: da801aa56ed9
Revises: 56a95c148237
Create Date: 2024-03-19 08:25:00.487435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da801aa56ed9'
down_revision: Union[str, None] = '56a95c148237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_files_tags',
    sa.Column('tag_id', sa.String(), nullable=True),
    sa.Column('secret_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['secret_file_id'], ['secret_files.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_files_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
